version: '2'
services:
  web:
    image: onrotation:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    command: mix phoenix.server
